/*
 * This source file was generated by the Gradle 'init' task
 */
package kbg.bean;

import kbg.bean.config.DIHandler;
import kbg.bean.domain.human.Human;
import kbg.bean.domain.weapon.Bow;
import kbg.bean.domain.weapon.Sword;
import kbg.bean.domain.weapon.Weapon;

public class Game {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        DIHandler diHandler = DIHandler.getInstance();

        Human h1 = diHandler.swordHuman();
        Human h2 = diHandler.bowHuman();

        h1.attack(h2);
        h2.attack(h1);
    }
}
