/*
 * This source file was generated by the Gradle 'init' task
 */
package kbg.bean;

import kbg.bean.domain.human.Human;
import kbg.bean.domain.weapon.Bow;
import kbg.bean.domain.weapon.Sword;
import kbg.bean.domain.weapon.Weapon;

public class Game {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Weapon sword = new Sword();
        Weapon bow = new Bow();

        Human h1 = new Human("기사", sword);
        Human h2 = new Human("궁수", bow);

        h1.attack(h2);
        h2.attack(h1);

    }
}
