/*
 * This source file was generated by the Gradle 'init' task
 */
package kbg.bean;

import kbg.bean.config.DIHandler;
import kbg.bean.domain.human.Human;
import kbg.bean.domain.weapon.Bow;
import kbg.bean.domain.weapon.Sword;
import kbg.bean.domain.weapon.Weapon;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class Game {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        ApplicationContext ctx = new ClassPathXmlApplicationContext("bean.xml");

        Human h1 = ctx.getBean("swordHuman", Human.class);
        Human h2 = ctx.getBean("bowHuman", Human.class);

        h1.attack(h2);
        h2.attack(h1);
    }
}
